### ISSUE TITLE
First Day of Week not working 

### ISSUE THREAD

**Issue by Sleeepy2** [atomic7777/atomic_calendar#18]
This is my config
```
defaultMode: 2
entities:
  - entity: calendar.sgmail_com
    type: icon2
firstDayOfWeek: 7
maxDaysToShow: 31
title: Sleep Home Calendar
type: 'custom:atomic-calendar'
```

The first day of the week shows as Sunday in the config however as soon as I save it it goes back to having Monday as the first day.
I am using version 0.7.4 of the calendar according to the updater, using version 0.94.3 Hass.io. 
Let me know if you need anything else.

**Comment by Sleeepy2** [comment]
Just realized that it is only the day headers that are off. So today is Thursday, July 4th and with Sunday as the start day of the calendar that would make today the 5th column. This is correct however the heading says Fri above today which is incorrect.
It also made me sad as I thought today was Friday :sob:

**Comment by atomic7777** [comment]
Should be fixed now in 0.8.3. Thanks for reporting. Sorry for making the weekend come too early :)

**Comment by Sleeepy2** [comment]
There must be something wrong with my lovelace setup? When I am editing/adding the card the day header lines up perfectly. When I click save to close the card, the day headers stay in place. As soon as I close the Configure UI the headers reset back to having Monday first.
Let me know if I can provide any other info to help me figure out what I have setup incorrectly.

Thanks

**Comment by atomic7777** [comment]
It could be because it loads an old version of calendar app sometimes (from cache).
Try to force reload the browser (ctrl-F5), or press F12 and go to Console and look if it says "Calendar v0.8.3 loaded" (it's the new version).
If you use HACS it should be better.

**Comment by Sleeepy2** [comment]
Yeah I am using HACS and is updated to 8.3 also did the F12 and Empty Cash and Hard Reload. Still happens. I use CCH so I tried disabling that also to see if it made a differences and it did not.

**Comment by Sleeepy2** [comment]
Wait, I just double checked the Console and it still says 8.2 loaded . I can't get it to load 8.3.
HACS says 8.3 is installed, I have re-installed and tried to uninstall and install again. Same thing.
Lets assume this is fixed for now and once I can figure out how to get it to load 8.3 I will let you know if I still have a problem.

Thanks for all your effort.
